// Icon resolution moved out of label-inference (regex rules) and into explicit
// per-answer / per-domain declarations in the JSON data files. The role of this
// module is now a small registry: map a lucide-react icon name (string) to the
// component, with a safe fallback.
//
// Why the rewrite: regex rules collided (mother & feminine → PersonStanding;
// both & both_fine & both_bother → Users), ~57 % of answers fell through to
// the ArrowRight fallback, and the rules were spread across two files (the
// regex list here and the labels in src/locales/*). Now the JSON is the single
// source of truth — see Answer.icon / Domain.icon in src/lib/dataset.ts.

import {
  // Default fallback
  ArrowRight,
  // People & roles
  Venus,
  Mars,
  Users,
  UsersRound,
  Baby,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  HandHelping,
  HelpingHand,
  Briefcase,
  // Yes / no / commitment
  ShieldCheck,
  Ban,
  X,
  BadgeX,
  BadgeCheck,
  CheckCheck,
  CircleSlash,
  SmilePlus,
  ThumbsUp,
  ThumbsDown,
  // Emotion
  Heart,
  HeartCrack,
  HeartPulse,
  HeartHandshake,
  Smile,
  Frown,
  Annoyed,
  Meh,
  // Nuance / time / frequency
  Bookmark,
  MinusCircle,
  BookOpen,
  Lightbulb,
  Hourglass,
  Clock,
  MessageCircle,
  Repeat,
  RotateCw,
  RotateCcw,
  Shuffle,
  CalendarDays,
  CalendarCheck,
  Scale,
  Gauge,
  TrendingUp,
  TrendingDown,
  ListChecks,
  HelpCircle,
  CircleHelp,
  Eye,
  EyeOff,
  Sparkles,
  Sprout,
  Wind,
  Zap,
  Lock,
  MoveRight,
  Target,
  Trophy,
  // Domain / task
  ChefHat,
  Wallet,
  Boxes,
  Footprints,
  Trash2,
  Bed,
  SprayCan,
  Fan,
  Sofa,
  UtensilsCrossed,
  ShoppingBasket,
  Salad,
  PartyPopper,
  School,
  Stethoscope,
  Hammer,
  HardHat,
  Plane,
  Car,
  PaintBucket,
  Megaphone,
  // Money
  Calculator,
  PiggyBank,
  Receipt,
  BadgeEuro,
  Banknote,
  Coins,
  FileText,
  Umbrella,
  // Couples / shared decisions
  Handshake,
  Award,
  Crown,
  Combine,
  Split,
  SplitSquareHorizontal,
  ArrowLeftRight,
  // Misc
  BatteryLow,
  type LucideIcon,
} from "lucide-react";

// The registry. Every lucide-react icon referenced from JSON data must appear
// here so the bundler can tree-shake correctly (a dynamic `Icons[name]` lookup
// on the whole `lucide-react` namespace would defeat tree-shaking).
const REGISTRY = {
  ArrowRight,
  Venus,
  Mars,
  Users,
  UsersRound,
  Baby,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  HandHelping,
  HelpingHand,
  Briefcase,
  ShieldCheck,
  Ban,
  X,
  BadgeX,
  BadgeCheck,
  CheckCheck,
  CircleSlash,
  SmilePlus,
  ThumbsUp,
  ThumbsDown,
  Heart,
  HeartCrack,
  HeartPulse,
  HeartHandshake,
  Smile,
  Frown,
  Annoyed,
  Meh,
  Bookmark,
  MinusCircle,
  BookOpen,
  Lightbulb,
  Hourglass,
  Clock,
  MessageCircle,
  Repeat,
  RotateCw,
  RotateCcw,
  Shuffle,
  CalendarDays,
  CalendarCheck,
  Scale,
  Gauge,
  TrendingUp,
  TrendingDown,
  ListChecks,
  HelpCircle,
  CircleHelp,
  Eye,
  EyeOff,
  Sparkles,
  Sprout,
  Wind,
  Zap,
  Lock,
  MoveRight,
  Target,
  Trophy,
  ChefHat,
  Wallet,
  Boxes,
  Footprints,
  Trash2,
  Bed,
  SprayCan,
  Fan,
  Sofa,
  UtensilsCrossed,
  ShoppingBasket,
  Salad,
  PartyPopper,
  School,
  Stethoscope,
  Hammer,
  HardHat,
  Plane,
  Car,
  PaintBucket,
  Megaphone,
  Calculator,
  PiggyBank,
  Receipt,
  BadgeEuro,
  Banknote,
  Coins,
  FileText,
  Umbrella,
  Handshake,
  Award,
  Crown,
  Combine,
  Split,
  SplitSquareHorizontal,
  ArrowLeftRight,
  BatteryLow,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof REGISTRY;

/**
 * Resolve an icon by name. If the name isn't registered (typo, new icon not
 * yet added to REGISTRY, missing field in JSON), logs a console.warn and
 * returns `ArrowRight` so the UI still renders.
 */
export function iconByName(name: string | undefined | null): LucideIcon {
  if (!name) return ArrowRight;
  const icon = (REGISTRY as Record<string, LucideIcon>)[name];
  if (!icon) {
    if (typeof console !== "undefined") {
      console.warn(`[icon-map] Unknown icon name "${name}" — falling back to ArrowRight`);
    }
    return ArrowRight;
  }
  return icon;
}
