/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleFoundationsRouteImport } from './routes/$locale/foundations'
import { Route as LocaleSCodeRouteImport } from './routes/$locale/s.$code'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFoundationsRoute = LocaleFoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSCodeRoute = LocaleSCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/foundations': typeof LocaleFoundationsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/s/$code': typeof LocaleSCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/foundations': typeof LocaleFoundationsRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/s/$code': typeof LocaleSCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/foundations': typeof LocaleFoundationsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/s/$code': typeof LocaleSCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/foundations'
    | '/$locale/'
    | '/$locale/s/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$locale/foundations' | '/$locale' | '/$locale/s/$code'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/foundations'
    | '/$locale/'
    | '/$locale/s/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/foundations': {
      id: '/$locale/foundations'
      path: '/foundations'
      fullPath: '/$locale/foundations'
      preLoaderRoute: typeof LocaleFoundationsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/s/$code': {
      id: '/$locale/s/$code'
      path: '/s/$code'
      fullPath: '/$locale/s/$code'
      preLoaderRoute: typeof LocaleSCodeRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleFoundationsRoute: typeof LocaleFoundationsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleSCodeRoute: typeof LocaleSCodeRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleFoundationsRoute: LocaleFoundationsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleSCodeRoute: LocaleSCodeRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
